version: 2

before:
  hooks:
    - go mod download

builds:
  - id: aws
    main: ./cmd/aws
    binary: executor_aws_{{ .Os }}_{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    no_unique_dist_dir: true

snapshot:
  version_template: 'v{{ .Version }}'
