name: Release Botkube plugins

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # dist/* 생성
      - name: Build plugins (snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --clean --snapshot

      - name: Generate plugins-index.yaml
        shell: bash
        run: |
          set -Eeuo pipefail
          TAG="${GITHUB_REF#refs/tags/}"
          BASE="https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG}"
          NAME="aws"
          TYPE="executor"
          DESC="Run AWS CLI from chat."
          VERSION="0.1.0"

          {
            printf "entries:\n"
            printf "  - name: %s\n" "$NAME"
            printf "    type: %s\n" "$TYPE"
            printf "    description: %s\n" "$DESC"
            printf "    version: %s\n" "$VERSION"
            printf "    urls:\n"
            if [[ -f dist/executor_aws_linux_amd64 ]]; then
              printf "    - url: %s/executor_aws_linux_amd64\n" "$BASE"
              printf "      platform:\n"
              printf "        os: linux\n"
              printf "        architecture: amd64\n"
            fi
            if [[ -f dist/executor_aws_linux_arm64 ]]; then
              printf "    - url: %s/executor_aws_linux_arm64\n" "$BASE"
              printf "      platform:\n"
              printf "        os: linux\n"
              printf "        architecture: arm64\n"
            fi
            printf "    jsonSchema:\n"
            printf "      value: |-\n"
          } > plugins-index.yaml

          cat >> plugins-index.yaml <<'JSON'
                {
                  "$schema":"http://json-schema.org/draft-04/schema#",
                  "title":"aws",
                  "type":"object",
                  "properties":{
                    "defaultRegion":{"type":"string"},
                    "prependArgs":{"type":"array","items":{"type":"string"}},
                    "allowed":{"type":"array","items":{"type":"string"}},
                    "env":{"type":"object","additionalProperties":{"type":"string"}}
                  },
                  "additionalProperties": false
                }
          JSON
          echo "    recommended: false" >> plugins-index.yaml

          echo "----- GENERATED INDEX -----"
          sed -n '1,200p' plugins-index.yaml

      - name: Create GitHub release & upload assets
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -Eeuo pipefail
          TAG="${GITHUB_REF#refs/tags/}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" --notes "Botkube plugins ${TAG}"
          shopt -s nullglob
          gh release upload "$TAG" dist/executor_* plugins-index.yaml --clobber
