name: Deploy Botkube plugins on GitHub Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # Build executor binaries into dist/
      - name: Build plugins
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --clean --snapshot

      # Enable arm64 emulation for Docker
      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build AWS CLI bundles (amd64 + arm64)
        run: make aws-bundle-all

      - name: Generate plugins-index.yaml
        env:
          PLUGIN_DOWNLOAD_URL_BASE_PATH: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        run: make gen-plugin-index

      - name: Create or update GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
          PLUGIN_DOWNLOAD_URL_BASE_PATH: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        run: make release-gh

      - name: Show index URL
        run: echo "Index URL => https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF#refs/tags/}/plugins-index.yaml"

