name: Deploy Botkube plugins on GitHub Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: latest

      - name: Build plugins and generate plugins index.yaml
        env:
          PLUGIN_DOWNLOAD_URL_BASE_PATH: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        run: |
          goreleaser build --clean --snapshot
          go run github.com/kubeshop/botkube/hack \
            -binaries-path "./dist" \
            -url-base-path "${PLUGIN_DOWNLOAD_URL_BASE_PATH}" \
            > plugins-index.yaml

      - name: Release description
        env:
          PLUGIN_DOWNLOAD_URL_BASE_PATH: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        run: |
          cat << EOF > release.md
          Botkube Plugins **${GITHUB_REF#refs/tags/}** are now available!
          To use them:
          ```yaml
          plugins:
            repositories:
              ${{ github.event.repository.name }}:
                url: ${PLUGIN_DOWNLOAD_URL_BASE_PATH}/plugins-index.yaml
          ```
          EOF

      - name: Create or update GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" --notes-file release.md

          shopt -s nullglob
          assets=(dist/executor_* plugins-index.yaml)  # dist/source_*는 아직 없음
          if ((${#assets[@]})); then
            gh release upload "$TAG" "${assets[@]}" --clobber
          fi
